namespace DoAn.NET
{
    partial class frmKhachHang
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmKhachHang));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panelMenu = new System.Windows.Forms.Panel();
            this.btnDangXuat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCaiDat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLichSuMua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDonHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnGioHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCuaHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTenDangNhap = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panelLogo = new System.Windows.Forms.Panel();
            this.labelLogo = new System.Windows.Forms.Label();
            this.panelTieuDe = new System.Windows.Forms.Panel();
            this.lblTieuDe = new System.Windows.Forms.Label();
            this.panelChildFrom = new System.Windows.Forms.Panel();
            this.panelMenu.SuspendLayout();
            this.panelLogo.SuspendLayout();
            this.panelTieuDe.SuspendLayout();
            this.SuspendLayout();
            // 
            // panelMenu
            // 
            this.panelMenu.AutoScroll = true;
            this.panelMenu.BackColor = System.Drawing.Color.DodgerBlue;
            this.panelMenu.Controls.Add(this.btnDangXuat);
            this.panelMenu.Controls.Add(this.btnCaiDat);
            this.panelMenu.Controls.Add(this.btnLichSuMua);
            this.panelMenu.Controls.Add(this.btnDonHang);
            this.panelMenu.Controls.Add(this.btnGioHang);
            this.panelMenu.Controls.Add(this.btnCuaHang);
            this.panelMenu.Controls.Add(this.btnTenDangNhap);
            this.panelMenu.Controls.Add(this.panelLogo);
            this.panelMenu.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelMenu.Location = new System.Drawing.Point(0, 0);
            this.panelMenu.Name = "panelMenu";
            this.panelMenu.Size = new System.Drawing.Size(250, 700);
            this.panelMenu.TabIndex = 0;
            // 
            // btnDangXuat
            // 
            this.btnDangXuat.AllowAnimations = true;
            this.btnDangXuat.AllowMouseEffects = true;
            this.btnDangXuat.AllowToggling = false;
            this.btnDangXuat.AnimationSpeed = 200;
            this.btnDangXuat.AutoGenerateColors = false;
            this.btnDangXuat.AutoRoundBorders = false;
            this.btnDangXuat.AutoSizeLeftIcon = true;
            this.btnDangXuat.AutoSizeRightIcon = true;
            this.btnDangXuat.BackColor = System.Drawing.Color.Transparent;
            this.btnDangXuat.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDangXuat.BackgroundImage")));
            this.btnDangXuat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.ButtonText = "ĐĂNG XUẤT";
            this.btnDangXuat.ButtonTextMarginLeft = 0;
            this.btnDangXuat.ColorContrastOnClick = 45;
            this.btnDangXuat.ColorContrastOnHover = 45;
            this.btnDangXuat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnDangXuat.CustomizableEdges = borderEdges1;
            this.btnDangXuat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDangXuat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDangXuat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDangXuat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDangXuat.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btnDangXuat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDangXuat.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnDangXuat.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDangXuat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDangXuat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDangXuat.IconMarginLeft = 11;
            this.btnDangXuat.IconPadding = 5;
            this.btnDangXuat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDangXuat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDangXuat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDangXuat.IconSize = 25;
            this.btnDangXuat.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.IdleBorderRadius = 40;
            this.btnDangXuat.IdleBorderThickness = 1;
            this.btnDangXuat.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.undo_480px;
            this.btnDangXuat.IdleIconRightImage = null;
            this.btnDangXuat.IndicateFocus = false;
            this.btnDangXuat.Location = new System.Drawing.Point(0, 655);
            this.btnDangXuat.Name = "btnDangXuat";
            this.btnDangXuat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDangXuat.OnDisabledState.BorderRadius = 40;
            this.btnDangXuat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnDisabledState.BorderThickness = 1;
            this.btnDangXuat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDangXuat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDangXuat.OnDisabledState.IconLeftImage = null;
            this.btnDangXuat.OnDisabledState.IconRightImage = null;
            this.btnDangXuat.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnDangXuat.onHoverState.BorderRadius = 40;
            this.btnDangXuat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.onHoverState.BorderThickness = 1;
            this.btnDangXuat.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnDangXuat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.onHoverState.IconLeftImage = null;
            this.btnDangXuat.onHoverState.IconRightImage = null;
            this.btnDangXuat.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.OnIdleState.BorderRadius = 40;
            this.btnDangXuat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnIdleState.BorderThickness = 1;
            this.btnDangXuat.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.undo_480px;
            this.btnDangXuat.OnIdleState.IconRightImage = null;
            this.btnDangXuat.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnDangXuat.OnPressedState.BorderRadius = 40;
            this.btnDangXuat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnPressedState.BorderThickness = 1;
            this.btnDangXuat.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnDangXuat.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.OnPressedState.IconLeftImage = null;
            this.btnDangXuat.OnPressedState.IconRightImage = null;
            this.btnDangXuat.Size = new System.Drawing.Size(250, 45);
            this.btnDangXuat.TabIndex = 14;
            this.btnDangXuat.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDangXuat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDangXuat.TextMarginLeft = 0;
            this.btnDangXuat.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnDangXuat.UseDefaultRadiusAndThickness = true;
            this.btnDangXuat.Click += new System.EventHandler(this.btnDangXuat_Click);
            // 
            // btnCaiDat
            // 
            this.btnCaiDat.AllowAnimations = true;
            this.btnCaiDat.AllowMouseEffects = true;
            this.btnCaiDat.AllowToggling = false;
            this.btnCaiDat.AnimationSpeed = 200;
            this.btnCaiDat.AutoGenerateColors = false;
            this.btnCaiDat.AutoRoundBorders = false;
            this.btnCaiDat.AutoSizeLeftIcon = true;
            this.btnCaiDat.AutoSizeRightIcon = true;
            this.btnCaiDat.BackColor = System.Drawing.Color.Transparent;
            this.btnCaiDat.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCaiDat.BackgroundImage")));
            this.btnCaiDat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.ButtonText = "CÀI ĐẶT";
            this.btnCaiDat.ButtonTextMarginLeft = 0;
            this.btnCaiDat.ColorContrastOnClick = 45;
            this.btnCaiDat.ColorContrastOnHover = 45;
            this.btnCaiDat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCaiDat.CustomizableEdges = borderEdges2;
            this.btnCaiDat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCaiDat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCaiDat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCaiDat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCaiDat.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCaiDat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCaiDat.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnCaiDat.ForeColor = System.Drawing.Color.White;
            this.btnCaiDat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCaiDat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCaiDat.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.btnCaiDat.IconMarginLeft = 11;
            this.btnCaiDat.IconPadding = 2;
            this.btnCaiDat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCaiDat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCaiDat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCaiDat.IconSize = 25;
            this.btnCaiDat.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.IdleBorderRadius = 40;
            this.btnCaiDat.IdleBorderThickness = 1;
            this.btnCaiDat.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.security_configuration_480px;
            this.btnCaiDat.IdleIconRightImage = null;
            this.btnCaiDat.IndicateFocus = false;
            this.btnCaiDat.Location = new System.Drawing.Point(0, 325);
            this.btnCaiDat.Name = "btnCaiDat";
            this.btnCaiDat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCaiDat.OnDisabledState.BorderRadius = 40;
            this.btnCaiDat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.OnDisabledState.BorderThickness = 1;
            this.btnCaiDat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCaiDat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCaiDat.OnDisabledState.IconLeftImage = null;
            this.btnCaiDat.OnDisabledState.IconRightImage = null;
            this.btnCaiDat.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnCaiDat.onHoverState.BorderRadius = 40;
            this.btnCaiDat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.onHoverState.BorderThickness = 1;
            this.btnCaiDat.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnCaiDat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCaiDat.onHoverState.IconLeftImage = null;
            this.btnCaiDat.onHoverState.IconRightImage = null;
            this.btnCaiDat.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.OnIdleState.BorderRadius = 40;
            this.btnCaiDat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.OnIdleState.BorderThickness = 1;
            this.btnCaiDat.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCaiDat.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.security_configuration_480px;
            this.btnCaiDat.OnIdleState.IconRightImage = null;
            this.btnCaiDat.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnCaiDat.OnPressedState.BorderRadius = 40;
            this.btnCaiDat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.OnPressedState.BorderThickness = 1;
            this.btnCaiDat.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnCaiDat.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.OnPressedState.IconLeftImage = null;
            this.btnCaiDat.OnPressedState.IconRightImage = null;
            this.btnCaiDat.Size = new System.Drawing.Size(250, 45);
            this.btnCaiDat.TabIndex = 13;
            this.btnCaiDat.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCaiDat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCaiDat.TextMarginLeft = 0;
            this.btnCaiDat.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnCaiDat.UseDefaultRadiusAndThickness = true;
            this.btnCaiDat.Click += new System.EventHandler(this.btnCaiDat_Click);
            // 
            // btnLichSuMua
            // 
            this.btnLichSuMua.AllowAnimations = true;
            this.btnLichSuMua.AllowMouseEffects = true;
            this.btnLichSuMua.AllowToggling = false;
            this.btnLichSuMua.AnimationSpeed = 200;
            this.btnLichSuMua.AutoGenerateColors = false;
            this.btnLichSuMua.AutoRoundBorders = false;
            this.btnLichSuMua.AutoSizeLeftIcon = true;
            this.btnLichSuMua.AutoSizeRightIcon = true;
            this.btnLichSuMua.BackColor = System.Drawing.Color.Transparent;
            this.btnLichSuMua.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnLichSuMua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLichSuMua.BackgroundImage")));
            this.btnLichSuMua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichSuMua.ButtonText = "LỊCH SỬ MUA";
            this.btnLichSuMua.ButtonTextMarginLeft = 0;
            this.btnLichSuMua.ColorContrastOnClick = 45;
            this.btnLichSuMua.ColorContrastOnHover = 45;
            this.btnLichSuMua.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnLichSuMua.CustomizableEdges = borderEdges3;
            this.btnLichSuMua.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLichSuMua.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLichSuMua.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLichSuMua.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLichSuMua.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnLichSuMua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLichSuMua.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnLichSuMua.ForeColor = System.Drawing.Color.White;
            this.btnLichSuMua.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLichSuMua.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLichSuMua.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.btnLichSuMua.IconMarginLeft = 11;
            this.btnLichSuMua.IconPadding = 5;
            this.btnLichSuMua.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLichSuMua.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLichSuMua.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLichSuMua.IconSize = 25;
            this.btnLichSuMua.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLichSuMua.IdleBorderRadius = 40;
            this.btnLichSuMua.IdleBorderThickness = 1;
            this.btnLichSuMua.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnLichSuMua.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.order_history_320px;
            this.btnLichSuMua.IdleIconRightImage = null;
            this.btnLichSuMua.IndicateFocus = false;
            this.btnLichSuMua.Location = new System.Drawing.Point(0, 280);
            this.btnLichSuMua.Name = "btnLichSuMua";
            this.btnLichSuMua.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLichSuMua.OnDisabledState.BorderRadius = 40;
            this.btnLichSuMua.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichSuMua.OnDisabledState.BorderThickness = 1;
            this.btnLichSuMua.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLichSuMua.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLichSuMua.OnDisabledState.IconLeftImage = null;
            this.btnLichSuMua.OnDisabledState.IconRightImage = null;
            this.btnLichSuMua.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnLichSuMua.onHoverState.BorderRadius = 40;
            this.btnLichSuMua.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichSuMua.onHoverState.BorderThickness = 1;
            this.btnLichSuMua.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnLichSuMua.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLichSuMua.onHoverState.IconLeftImage = null;
            this.btnLichSuMua.onHoverState.IconRightImage = null;
            this.btnLichSuMua.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLichSuMua.OnIdleState.BorderRadius = 40;
            this.btnLichSuMua.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichSuMua.OnIdleState.BorderThickness = 1;
            this.btnLichSuMua.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnLichSuMua.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLichSuMua.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.order_history_320px;
            this.btnLichSuMua.OnIdleState.IconRightImage = null;
            this.btnLichSuMua.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnLichSuMua.OnPressedState.BorderRadius = 40;
            this.btnLichSuMua.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichSuMua.OnPressedState.BorderThickness = 1;
            this.btnLichSuMua.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnLichSuMua.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnLichSuMua.OnPressedState.IconLeftImage = null;
            this.btnLichSuMua.OnPressedState.IconRightImage = null;
            this.btnLichSuMua.Size = new System.Drawing.Size(250, 45);
            this.btnLichSuMua.TabIndex = 12;
            this.btnLichSuMua.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLichSuMua.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLichSuMua.TextMarginLeft = 0;
            this.btnLichSuMua.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnLichSuMua.UseDefaultRadiusAndThickness = true;
            this.btnLichSuMua.Click += new System.EventHandler(this.btnLichSuMua_Click);
            // 
            // btnDonHang
            // 
            this.btnDonHang.AllowAnimations = true;
            this.btnDonHang.AllowMouseEffects = true;
            this.btnDonHang.AllowToggling = false;
            this.btnDonHang.AnimationSpeed = 200;
            this.btnDonHang.AutoGenerateColors = false;
            this.btnDonHang.AutoRoundBorders = false;
            this.btnDonHang.AutoSizeLeftIcon = true;
            this.btnDonHang.AutoSizeRightIcon = true;
            this.btnDonHang.BackColor = System.Drawing.Color.Transparent;
            this.btnDonHang.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnDonHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDonHang.BackgroundImage")));
            this.btnDonHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDonHang.ButtonText = "ĐƠN HÀNG";
            this.btnDonHang.ButtonTextMarginLeft = 0;
            this.btnDonHang.ColorContrastOnClick = 45;
            this.btnDonHang.ColorContrastOnHover = 45;
            this.btnDonHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnDonHang.CustomizableEdges = borderEdges4;
            this.btnDonHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDonHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDonHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDonHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDonHang.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnDonHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDonHang.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnDonHang.ForeColor = System.Drawing.Color.White;
            this.btnDonHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDonHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDonHang.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.btnDonHang.IconMarginLeft = 11;
            this.btnDonHang.IconPadding = 5;
            this.btnDonHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDonHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDonHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDonHang.IconSize = 25;
            this.btnDonHang.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDonHang.IdleBorderRadius = 40;
            this.btnDonHang.IdleBorderThickness = 1;
            this.btnDonHang.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnDonHang.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.purchase_order_320px;
            this.btnDonHang.IdleIconRightImage = null;
            this.btnDonHang.IndicateFocus = false;
            this.btnDonHang.Location = new System.Drawing.Point(0, 235);
            this.btnDonHang.Name = "btnDonHang";
            this.btnDonHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDonHang.OnDisabledState.BorderRadius = 40;
            this.btnDonHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDonHang.OnDisabledState.BorderThickness = 1;
            this.btnDonHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDonHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDonHang.OnDisabledState.IconLeftImage = null;
            this.btnDonHang.OnDisabledState.IconRightImage = null;
            this.btnDonHang.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnDonHang.onHoverState.BorderRadius = 40;
            this.btnDonHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDonHang.onHoverState.BorderThickness = 1;
            this.btnDonHang.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnDonHang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDonHang.onHoverState.IconLeftImage = null;
            this.btnDonHang.onHoverState.IconRightImage = null;
            this.btnDonHang.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDonHang.OnIdleState.BorderRadius = 40;
            this.btnDonHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDonHang.OnIdleState.BorderThickness = 1;
            this.btnDonHang.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDonHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDonHang.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.purchase_order_320px;
            this.btnDonHang.OnIdleState.IconRightImage = null;
            this.btnDonHang.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnDonHang.OnPressedState.BorderRadius = 40;
            this.btnDonHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDonHang.OnPressedState.BorderThickness = 1;
            this.btnDonHang.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnDonHang.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnDonHang.OnPressedState.IconLeftImage = null;
            this.btnDonHang.OnPressedState.IconRightImage = null;
            this.btnDonHang.Size = new System.Drawing.Size(250, 45);
            this.btnDonHang.TabIndex = 11;
            this.btnDonHang.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDonHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDonHang.TextMarginLeft = 0;
            this.btnDonHang.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnDonHang.UseDefaultRadiusAndThickness = true;
            this.btnDonHang.Click += new System.EventHandler(this.btnDonHang_Click);
            // 
            // btnGioHang
            // 
            this.btnGioHang.AllowAnimations = true;
            this.btnGioHang.AllowMouseEffects = true;
            this.btnGioHang.AllowToggling = false;
            this.btnGioHang.AnimationSpeed = 200;
            this.btnGioHang.AutoGenerateColors = false;
            this.btnGioHang.AutoRoundBorders = false;
            this.btnGioHang.AutoSizeLeftIcon = true;
            this.btnGioHang.AutoSizeRightIcon = true;
            this.btnGioHang.BackColor = System.Drawing.Color.Transparent;
            this.btnGioHang.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnGioHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGioHang.BackgroundImage")));
            this.btnGioHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioHang.ButtonText = "GIỎ HÀNG";
            this.btnGioHang.ButtonTextMarginLeft = 0;
            this.btnGioHang.ColorContrastOnClick = 45;
            this.btnGioHang.ColorContrastOnHover = 45;
            this.btnGioHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnGioHang.CustomizableEdges = borderEdges5;
            this.btnGioHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGioHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGioHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGioHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGioHang.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnGioHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGioHang.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnGioHang.ForeColor = System.Drawing.Color.White;
            this.btnGioHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGioHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGioHang.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.btnGioHang.IconMarginLeft = 11;
            this.btnGioHang.IconPadding = 3;
            this.btnGioHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGioHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGioHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGioHang.IconSize = 25;
            this.btnGioHang.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnGioHang.IdleBorderRadius = 40;
            this.btnGioHang.IdleBorderThickness = 1;
            this.btnGioHang.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnGioHang.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.shopping_basket_320px;
            this.btnGioHang.IdleIconRightImage = null;
            this.btnGioHang.IndicateFocus = false;
            this.btnGioHang.Location = new System.Drawing.Point(0, 190);
            this.btnGioHang.Name = "btnGioHang";
            this.btnGioHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGioHang.OnDisabledState.BorderRadius = 40;
            this.btnGioHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioHang.OnDisabledState.BorderThickness = 1;
            this.btnGioHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGioHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGioHang.OnDisabledState.IconLeftImage = null;
            this.btnGioHang.OnDisabledState.IconRightImage = null;
            this.btnGioHang.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnGioHang.onHoverState.BorderRadius = 40;
            this.btnGioHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioHang.onHoverState.BorderThickness = 1;
            this.btnGioHang.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnGioHang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGioHang.onHoverState.IconLeftImage = null;
            this.btnGioHang.onHoverState.IconRightImage = null;
            this.btnGioHang.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnGioHang.OnIdleState.BorderRadius = 40;
            this.btnGioHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioHang.OnIdleState.BorderThickness = 1;
            this.btnGioHang.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnGioHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGioHang.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.shopping_basket_320px;
            this.btnGioHang.OnIdleState.IconRightImage = null;
            this.btnGioHang.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnGioHang.OnPressedState.BorderRadius = 40;
            this.btnGioHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioHang.OnPressedState.BorderThickness = 1;
            this.btnGioHang.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnGioHang.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnGioHang.OnPressedState.IconLeftImage = null;
            this.btnGioHang.OnPressedState.IconRightImage = null;
            this.btnGioHang.Size = new System.Drawing.Size(250, 45);
            this.btnGioHang.TabIndex = 10;
            this.btnGioHang.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGioHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGioHang.TextMarginLeft = 0;
            this.btnGioHang.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnGioHang.UseDefaultRadiusAndThickness = true;
            this.btnGioHang.Click += new System.EventHandler(this.btnGioHang_Click);
            // 
            // btnCuaHang
            // 
            this.btnCuaHang.AllowAnimations = true;
            this.btnCuaHang.AllowMouseEffects = true;
            this.btnCuaHang.AllowToggling = false;
            this.btnCuaHang.AnimationSpeed = 200;
            this.btnCuaHang.AutoGenerateColors = false;
            this.btnCuaHang.AutoRoundBorders = false;
            this.btnCuaHang.AutoSizeLeftIcon = true;
            this.btnCuaHang.AutoSizeRightIcon = true;
            this.btnCuaHang.BackColor = System.Drawing.Color.Transparent;
            this.btnCuaHang.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnCuaHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCuaHang.BackgroundImage")));
            this.btnCuaHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCuaHang.ButtonText = "CỬA HÀNG";
            this.btnCuaHang.ButtonTextMarginLeft = 0;
            this.btnCuaHang.ColorContrastOnClick = 45;
            this.btnCuaHang.ColorContrastOnHover = 45;
            this.btnCuaHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnCuaHang.CustomizableEdges = borderEdges6;
            this.btnCuaHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCuaHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCuaHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCuaHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCuaHang.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCuaHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCuaHang.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnCuaHang.ForeColor = System.Drawing.Color.White;
            this.btnCuaHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCuaHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCuaHang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCuaHang.IconMarginLeft = 11;
            this.btnCuaHang.IconPadding = 6;
            this.btnCuaHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCuaHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCuaHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCuaHang.IconSize = 25;
            this.btnCuaHang.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCuaHang.IdleBorderRadius = 40;
            this.btnCuaHang.IdleBorderThickness = 1;
            this.btnCuaHang.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnCuaHang.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.shop_320px;
            this.btnCuaHang.IdleIconRightImage = null;
            this.btnCuaHang.IndicateFocus = false;
            this.btnCuaHang.Location = new System.Drawing.Point(0, 145);
            this.btnCuaHang.Name = "btnCuaHang";
            this.btnCuaHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCuaHang.OnDisabledState.BorderRadius = 40;
            this.btnCuaHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCuaHang.OnDisabledState.BorderThickness = 1;
            this.btnCuaHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCuaHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCuaHang.OnDisabledState.IconLeftImage = null;
            this.btnCuaHang.OnDisabledState.IconRightImage = null;
            this.btnCuaHang.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnCuaHang.onHoverState.BorderRadius = 40;
            this.btnCuaHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCuaHang.onHoverState.BorderThickness = 1;
            this.btnCuaHang.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnCuaHang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCuaHang.onHoverState.IconLeftImage = null;
            this.btnCuaHang.onHoverState.IconRightImage = null;
            this.btnCuaHang.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCuaHang.OnIdleState.BorderRadius = 40;
            this.btnCuaHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCuaHang.OnIdleState.BorderThickness = 1;
            this.btnCuaHang.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCuaHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCuaHang.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.shop_320px;
            this.btnCuaHang.OnIdleState.IconRightImage = null;
            this.btnCuaHang.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnCuaHang.OnPressedState.BorderRadius = 40;
            this.btnCuaHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCuaHang.OnPressedState.BorderThickness = 1;
            this.btnCuaHang.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnCuaHang.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnCuaHang.OnPressedState.IconLeftImage = null;
            this.btnCuaHang.OnPressedState.IconRightImage = null;
            this.btnCuaHang.Size = new System.Drawing.Size(250, 45);
            this.btnCuaHang.TabIndex = 9;
            this.btnCuaHang.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCuaHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCuaHang.TextMarginLeft = 0;
            this.btnCuaHang.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnCuaHang.UseDefaultRadiusAndThickness = true;
            this.btnCuaHang.Click += new System.EventHandler(this.btnCuaHang_Click);
            // 
            // btnTenDangNhap
            // 
            this.btnTenDangNhap.AllowAnimations = true;
            this.btnTenDangNhap.AllowMouseEffects = true;
            this.btnTenDangNhap.AllowToggling = false;
            this.btnTenDangNhap.AnimationSpeed = 200;
            this.btnTenDangNhap.AutoGenerateColors = false;
            this.btnTenDangNhap.AutoRoundBorders = false;
            this.btnTenDangNhap.AutoSizeLeftIcon = true;
            this.btnTenDangNhap.AutoSizeRightIcon = true;
            this.btnTenDangNhap.BackColor = System.Drawing.Color.Transparent;
            this.btnTenDangNhap.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnTenDangNhap.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTenDangNhap.BackgroundImage")));
            this.btnTenDangNhap.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTenDangNhap.ButtonText = "TÊN ĐĂNG NHẬP";
            this.btnTenDangNhap.ButtonTextMarginLeft = 0;
            this.btnTenDangNhap.ColorContrastOnClick = 45;
            this.btnTenDangNhap.ColorContrastOnHover = 45;
            this.btnTenDangNhap.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnTenDangNhap.CustomizableEdges = borderEdges7;
            this.btnTenDangNhap.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTenDangNhap.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTenDangNhap.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTenDangNhap.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTenDangNhap.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnTenDangNhap.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTenDangNhap.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnTenDangNhap.ForeColor = System.Drawing.Color.White;
            this.btnTenDangNhap.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTenDangNhap.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTenDangNhap.IconLeftPadding = new System.Windows.Forms.Padding(5, 3, 3, 3);
            this.btnTenDangNhap.IconMarginLeft = 11;
            this.btnTenDangNhap.IconPadding = 0;
            this.btnTenDangNhap.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTenDangNhap.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTenDangNhap.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTenDangNhap.IconSize = 25;
            this.btnTenDangNhap.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnTenDangNhap.IdleBorderRadius = 40;
            this.btnTenDangNhap.IdleBorderThickness = 1;
            this.btnTenDangNhap.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnTenDangNhap.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.popular_man_500px;
            this.btnTenDangNhap.IdleIconRightImage = null;
            this.btnTenDangNhap.IndicateFocus = false;
            this.btnTenDangNhap.Location = new System.Drawing.Point(0, 100);
            this.btnTenDangNhap.Name = "btnTenDangNhap";
            this.btnTenDangNhap.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTenDangNhap.OnDisabledState.BorderRadius = 40;
            this.btnTenDangNhap.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTenDangNhap.OnDisabledState.BorderThickness = 1;
            this.btnTenDangNhap.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTenDangNhap.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTenDangNhap.OnDisabledState.IconLeftImage = null;
            this.btnTenDangNhap.OnDisabledState.IconRightImage = null;
            this.btnTenDangNhap.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnTenDangNhap.onHoverState.BorderRadius = 40;
            this.btnTenDangNhap.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTenDangNhap.onHoverState.BorderThickness = 1;
            this.btnTenDangNhap.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnTenDangNhap.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTenDangNhap.onHoverState.IconLeftImage = null;
            this.btnTenDangNhap.onHoverState.IconRightImage = null;
            this.btnTenDangNhap.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnTenDangNhap.OnIdleState.BorderRadius = 40;
            this.btnTenDangNhap.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTenDangNhap.OnIdleState.BorderThickness = 1;
            this.btnTenDangNhap.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnTenDangNhap.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTenDangNhap.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.popular_man_500px;
            this.btnTenDangNhap.OnIdleState.IconRightImage = null;
            this.btnTenDangNhap.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnTenDangNhap.OnPressedState.BorderRadius = 40;
            this.btnTenDangNhap.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTenDangNhap.OnPressedState.BorderThickness = 1;
            this.btnTenDangNhap.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnTenDangNhap.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnTenDangNhap.OnPressedState.IconLeftImage = null;
            this.btnTenDangNhap.OnPressedState.IconRightImage = null;
            this.btnTenDangNhap.Size = new System.Drawing.Size(250, 45);
            this.btnTenDangNhap.TabIndex = 8;
            this.btnTenDangNhap.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTenDangNhap.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTenDangNhap.TextMarginLeft = 0;
            this.btnTenDangNhap.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnTenDangNhap.UseDefaultRadiusAndThickness = true;
            this.btnTenDangNhap.Click += new System.EventHandler(this.btnTenDangNhap_Click);
            // 
            // panelLogo
            // 
            this.panelLogo.BackColor = System.Drawing.Color.DodgerBlue;
            this.panelLogo.Controls.Add(this.labelLogo);
            this.panelLogo.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelLogo.Location = new System.Drawing.Point(0, 0);
            this.panelLogo.Name = "panelLogo";
            this.panelLogo.Size = new System.Drawing.Size(250, 100);
            this.panelLogo.TabIndex = 0;
            this.panelLogo.Click += new System.EventHandler(this.panelLogo_Click);
            // 
            // labelLogo
            // 
            this.labelLogo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.labelLogo.Font = new System.Drawing.Font("Segoe Print", 34F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelLogo.ForeColor = System.Drawing.Color.White;
            this.labelLogo.Location = new System.Drawing.Point(0, 0);
            this.labelLogo.Name = "labelLogo";
            this.labelLogo.Size = new System.Drawing.Size(250, 100);
            this.labelLogo.TabIndex = 0;
            this.labelLogo.Text = "NK";
            this.labelLogo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panelTieuDe
            // 
            this.panelTieuDe.Controls.Add(this.lblTieuDe);
            this.panelTieuDe.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTieuDe.Location = new System.Drawing.Point(250, 0);
            this.panelTieuDe.Name = "panelTieuDe";
            this.panelTieuDe.Size = new System.Drawing.Size(850, 45);
            this.panelTieuDe.TabIndex = 1;
            // 
            // lblTieuDe
            // 
            this.lblTieuDe.BackColor = System.Drawing.Color.White;
            this.lblTieuDe.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTieuDe.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTieuDe.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(133)))), ((int)(((byte)(226)))));
            this.lblTieuDe.Location = new System.Drawing.Point(0, 0);
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.Size = new System.Drawing.Size(850, 45);
            this.lblTieuDe.TabIndex = 0;
            this.lblTieuDe.Text = "TRANG CHỦ";
            this.lblTieuDe.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panelChildFrom
            // 
            this.panelChildFrom.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelChildFrom.Location = new System.Drawing.Point(250, 45);
            this.panelChildFrom.Name = "panelChildFrom";
            this.panelChildFrom.Size = new System.Drawing.Size(850, 655);
            this.panelChildFrom.TabIndex = 2;
            // 
            // frmKhachHang
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(12F, 25F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.Controls.Add(this.panelChildFrom);
            this.Controls.Add(this.panelTieuDe);
            this.Controls.Add(this.panelMenu);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MinimumSize = new System.Drawing.Size(1100, 700);
            this.Name = "frmKhachHang";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Trang chủ";
            this.Load += new System.EventHandler(this.frmKhachHang_Load);
            this.panelMenu.ResumeLayout(false);
            this.panelLogo.ResumeLayout(false);
            this.panelTieuDe.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panelMenu;
        private System.Windows.Forms.Panel panelLogo;
        private System.Windows.Forms.Panel panelTieuDe;
        private System.Windows.Forms.Label lblTieuDe;
        private System.Windows.Forms.Panel panelChildFrom;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTenDangNhap;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCaiDat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLichSuMua;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDonHang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGioHang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCuaHang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDangXuat;
        private System.Windows.Forms.Label labelLogo;
    }
}