namespace DoAn.NET
{
    partial class frmAdmin
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmAdmin));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panelMenu = new System.Windows.Forms.Panel();
            this.panelLogo = new System.Windows.Forms.Panel();
            this.labelLogo = new System.Windows.Forms.Label();
            this.panelTieuDe = new System.Windows.Forms.Panel();
            this.lbTieuDe = new System.Windows.Forms.Label();
            this.panelForm = new System.Windows.Forms.Panel();
            this.btnDangXuat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCaiDat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThongKe = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHoaDon = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnKho = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSanPham = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnKhachHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panelMenu.SuspendLayout();
            this.panelLogo.SuspendLayout();
            this.panelTieuDe.SuspendLayout();
            this.SuspendLayout();
            // 
            // panelMenu
            // 
            this.panelMenu.AutoScroll = true;
            this.panelMenu.BackColor = System.Drawing.Color.DodgerBlue;
            this.panelMenu.Controls.Add(this.btnDangXuat);
            this.panelMenu.Controls.Add(this.btnCaiDat);
            this.panelMenu.Controls.Add(this.btnThongKe);
            this.panelMenu.Controls.Add(this.btnHoaDon);
            this.panelMenu.Controls.Add(this.btnKho);
            this.panelMenu.Controls.Add(this.btnSanPham);
            this.panelMenu.Controls.Add(this.btnKhachHang);
            this.panelMenu.Controls.Add(this.panelLogo);
            this.panelMenu.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelMenu.Location = new System.Drawing.Point(0, 0);
            this.panelMenu.Name = "panelMenu";
            this.panelMenu.Size = new System.Drawing.Size(250, 702);
            this.panelMenu.TabIndex = 8;
            // 
            // panelLogo
            // 
            this.panelLogo.BackColor = System.Drawing.Color.DodgerBlue;
            this.panelLogo.Controls.Add(this.labelLogo);
            this.panelLogo.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelLogo.Location = new System.Drawing.Point(0, 0);
            this.panelLogo.Name = "panelLogo";
            this.panelLogo.Size = new System.Drawing.Size(250, 100);
            this.panelLogo.TabIndex = 0;
            // 
            // labelLogo
            // 
            this.labelLogo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.labelLogo.Font = new System.Drawing.Font("Segoe Print", 34F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelLogo.ForeColor = System.Drawing.Color.White;
            this.labelLogo.Location = new System.Drawing.Point(0, 0);
            this.labelLogo.Name = "labelLogo";
            this.labelLogo.Size = new System.Drawing.Size(250, 100);
            this.labelLogo.TabIndex = 0;
            this.labelLogo.Text = "NK";
            this.labelLogo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.labelLogo.Click += new System.EventHandler(this.labelLogo_Click);
            // 
            // panelTieuDe
            // 
            this.panelTieuDe.Controls.Add(this.lbTieuDe);
            this.panelTieuDe.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTieuDe.Location = new System.Drawing.Point(250, 0);
            this.panelTieuDe.Name = "panelTieuDe";
            this.panelTieuDe.Size = new System.Drawing.Size(967, 45);
            this.panelTieuDe.TabIndex = 9;
            // 
            // lbTieuDe
            // 
            this.lbTieuDe.BackColor = System.Drawing.Color.White;
            this.lbTieuDe.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lbTieuDe.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbTieuDe.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(133)))), ((int)(((byte)(226)))));
            this.lbTieuDe.Location = new System.Drawing.Point(0, 0);
            this.lbTieuDe.Name = "lbTieuDe";
            this.lbTieuDe.Size = new System.Drawing.Size(967, 45);
            this.lbTieuDe.TabIndex = 0;
            this.lbTieuDe.Text = "TRANG CHỦ ADMIN";
            this.lbTieuDe.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panelForm
            // 
            this.panelForm.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelForm.Location = new System.Drawing.Point(250, 45);
            this.panelForm.Name = "panelForm";
            this.panelForm.Size = new System.Drawing.Size(967, 657);
            this.panelForm.TabIndex = 10;
            // 
            // btnDangXuat
            // 
            this.btnDangXuat.AllowAnimations = true;
            this.btnDangXuat.AllowMouseEffects = true;
            this.btnDangXuat.AllowToggling = false;
            this.btnDangXuat.AnimationSpeed = 200;
            this.btnDangXuat.AutoGenerateColors = false;
            this.btnDangXuat.AutoRoundBorders = false;
            this.btnDangXuat.AutoSizeLeftIcon = true;
            this.btnDangXuat.AutoSizeRightIcon = true;
            this.btnDangXuat.BackColor = System.Drawing.Color.Transparent;
            this.btnDangXuat.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDangXuat.BackgroundImage")));
            this.btnDangXuat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.ButtonText = "ĐĂNG XUẤT";
            this.btnDangXuat.ButtonTextMarginLeft = 0;
            this.btnDangXuat.ColorContrastOnClick = 45;
            this.btnDangXuat.ColorContrastOnHover = 45;
            this.btnDangXuat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnDangXuat.CustomizableEdges = borderEdges1;
            this.btnDangXuat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDangXuat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDangXuat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDangXuat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDangXuat.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btnDangXuat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDangXuat.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnDangXuat.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDangXuat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDangXuat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDangXuat.IconMarginLeft = 11;
            this.btnDangXuat.IconPadding = 5;
            this.btnDangXuat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDangXuat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDangXuat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDangXuat.IconSize = 25;
            this.btnDangXuat.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.IdleBorderRadius = 40;
            this.btnDangXuat.IdleBorderThickness = 1;
            this.btnDangXuat.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.undo_480px;
            this.btnDangXuat.IdleIconRightImage = null;
            this.btnDangXuat.IndicateFocus = false;
            this.btnDangXuat.Location = new System.Drawing.Point(0, 657);
            this.btnDangXuat.Name = "btnDangXuat";
            this.btnDangXuat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDangXuat.OnDisabledState.BorderRadius = 40;
            this.btnDangXuat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnDisabledState.BorderThickness = 1;
            this.btnDangXuat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDangXuat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDangXuat.OnDisabledState.IconLeftImage = null;
            this.btnDangXuat.OnDisabledState.IconRightImage = null;
            this.btnDangXuat.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnDangXuat.onHoverState.BorderRadius = 40;
            this.btnDangXuat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.onHoverState.BorderThickness = 1;
            this.btnDangXuat.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnDangXuat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.onHoverState.IconLeftImage = null;
            this.btnDangXuat.onHoverState.IconRightImage = null;
            this.btnDangXuat.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.OnIdleState.BorderRadius = 40;
            this.btnDangXuat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnIdleState.BorderThickness = 1;
            this.btnDangXuat.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.undo_480px;
            this.btnDangXuat.OnIdleState.IconRightImage = null;
            this.btnDangXuat.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnDangXuat.OnPressedState.BorderRadius = 40;
            this.btnDangXuat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnPressedState.BorderThickness = 1;
            this.btnDangXuat.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnDangXuat.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.OnPressedState.IconLeftImage = null;
            this.btnDangXuat.OnPressedState.IconRightImage = null;
            this.btnDangXuat.Size = new System.Drawing.Size(250, 45);
            this.btnDangXuat.TabIndex = 14;
            this.btnDangXuat.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDangXuat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDangXuat.TextMarginLeft = 0;
            this.btnDangXuat.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnDangXuat.UseDefaultRadiusAndThickness = true;
            this.btnDangXuat.Click += new System.EventHandler(this.btnDangXuat_Click);
            // 
            // btnCaiDat
            // 
            this.btnCaiDat.AllowAnimations = true;
            this.btnCaiDat.AllowMouseEffects = true;
            this.btnCaiDat.AllowToggling = false;
            this.btnCaiDat.AnimationSpeed = 200;
            this.btnCaiDat.AutoGenerateColors = false;
            this.btnCaiDat.AutoRoundBorders = false;
            this.btnCaiDat.AutoSizeLeftIcon = true;
            this.btnCaiDat.AutoSizeRightIcon = true;
            this.btnCaiDat.BackColor = System.Drawing.Color.Transparent;
            this.btnCaiDat.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCaiDat.BackgroundImage")));
            this.btnCaiDat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.ButtonText = "CÀI ĐẶT";
            this.btnCaiDat.ButtonTextMarginLeft = 0;
            this.btnCaiDat.ColorContrastOnClick = 45;
            this.btnCaiDat.ColorContrastOnHover = 45;
            this.btnCaiDat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCaiDat.CustomizableEdges = borderEdges2;
            this.btnCaiDat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCaiDat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCaiDat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCaiDat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCaiDat.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCaiDat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCaiDat.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnCaiDat.ForeColor = System.Drawing.Color.White;
            this.btnCaiDat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCaiDat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCaiDat.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.btnCaiDat.IconMarginLeft = 11;
            this.btnCaiDat.IconPadding = 2;
            this.btnCaiDat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCaiDat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCaiDat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCaiDat.IconSize = 25;
            this.btnCaiDat.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.IdleBorderRadius = 40;
            this.btnCaiDat.IdleBorderThickness = 1;
            this.btnCaiDat.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.security_configuration_480px;
            this.btnCaiDat.IdleIconRightImage = null;
            this.btnCaiDat.IndicateFocus = false;
            this.btnCaiDat.Location = new System.Drawing.Point(0, 325);
            this.btnCaiDat.Name = "btnCaiDat";
            this.btnCaiDat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCaiDat.OnDisabledState.BorderRadius = 40;
            this.btnCaiDat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.OnDisabledState.BorderThickness = 1;
            this.btnCaiDat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCaiDat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCaiDat.OnDisabledState.IconLeftImage = null;
            this.btnCaiDat.OnDisabledState.IconRightImage = null;
            this.btnCaiDat.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnCaiDat.onHoverState.BorderRadius = 40;
            this.btnCaiDat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.onHoverState.BorderThickness = 1;
            this.btnCaiDat.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnCaiDat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCaiDat.onHoverState.IconLeftImage = null;
            this.btnCaiDat.onHoverState.IconRightImage = null;
            this.btnCaiDat.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.OnIdleState.BorderRadius = 40;
            this.btnCaiDat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.OnIdleState.BorderThickness = 1;
            this.btnCaiDat.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCaiDat.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.security_configuration_480px;
            this.btnCaiDat.OnIdleState.IconRightImage = null;
            this.btnCaiDat.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnCaiDat.OnPressedState.BorderRadius = 40;
            this.btnCaiDat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCaiDat.OnPressedState.BorderThickness = 1;
            this.btnCaiDat.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnCaiDat.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnCaiDat.OnPressedState.IconLeftImage = null;
            this.btnCaiDat.OnPressedState.IconRightImage = null;
            this.btnCaiDat.Size = new System.Drawing.Size(250, 45);
            this.btnCaiDat.TabIndex = 13;
            this.btnCaiDat.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCaiDat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCaiDat.TextMarginLeft = 0;
            this.btnCaiDat.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnCaiDat.UseDefaultRadiusAndThickness = true;
            this.btnCaiDat.Click += new System.EventHandler(this.btnCaiDat_Click);
            // 
            // btnThongKe
            // 
            this.btnThongKe.AllowAnimations = true;
            this.btnThongKe.AllowMouseEffects = true;
            this.btnThongKe.AllowToggling = false;
            this.btnThongKe.AnimationSpeed = 200;
            this.btnThongKe.AutoGenerateColors = false;
            this.btnThongKe.AutoRoundBorders = false;
            this.btnThongKe.AutoSizeLeftIcon = true;
            this.btnThongKe.AutoSizeRightIcon = true;
            this.btnThongKe.BackColor = System.Drawing.Color.Transparent;
            this.btnThongKe.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnThongKe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThongKe.BackgroundImage")));
            this.btnThongKe.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.ButtonText = "THỐNG KÊ";
            this.btnThongKe.ButtonTextMarginLeft = 0;
            this.btnThongKe.ColorContrastOnClick = 45;
            this.btnThongKe.ColorContrastOnHover = 45;
            this.btnThongKe.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnThongKe.CustomizableEdges = borderEdges3;
            this.btnThongKe.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThongKe.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThongKe.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThongKe.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThongKe.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnThongKe.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThongKe.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnThongKe.ForeColor = System.Drawing.Color.White;
            this.btnThongKe.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThongKe.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThongKe.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.btnThongKe.IconMarginLeft = 11;
            this.btnThongKe.IconPadding = 5;
            this.btnThongKe.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThongKe.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThongKe.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThongKe.IconSize = 25;
            this.btnThongKe.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnThongKe.IdleBorderRadius = 40;
            this.btnThongKe.IdleBorderThickness = 1;
            this.btnThongKe.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnThongKe.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.order_history_320px;
            this.btnThongKe.IdleIconRightImage = null;
            this.btnThongKe.IndicateFocus = false;
            this.btnThongKe.Location = new System.Drawing.Point(0, 280);
            this.btnThongKe.Name = "btnThongKe";
            this.btnThongKe.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThongKe.OnDisabledState.BorderRadius = 40;
            this.btnThongKe.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.OnDisabledState.BorderThickness = 1;
            this.btnThongKe.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThongKe.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThongKe.OnDisabledState.IconLeftImage = null;
            this.btnThongKe.OnDisabledState.IconRightImage = null;
            this.btnThongKe.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnThongKe.onHoverState.BorderRadius = 40;
            this.btnThongKe.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.onHoverState.BorderThickness = 1;
            this.btnThongKe.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnThongKe.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThongKe.onHoverState.IconLeftImage = null;
            this.btnThongKe.onHoverState.IconRightImage = null;
            this.btnThongKe.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnThongKe.OnIdleState.BorderRadius = 40;
            this.btnThongKe.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.OnIdleState.BorderThickness = 1;
            this.btnThongKe.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnThongKe.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThongKe.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.order_history_320px;
            this.btnThongKe.OnIdleState.IconRightImage = null;
            this.btnThongKe.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnThongKe.OnPressedState.BorderRadius = 40;
            this.btnThongKe.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongKe.OnPressedState.BorderThickness = 1;
            this.btnThongKe.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnThongKe.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnThongKe.OnPressedState.IconLeftImage = null;
            this.btnThongKe.OnPressedState.IconRightImage = null;
            this.btnThongKe.Size = new System.Drawing.Size(250, 45);
            this.btnThongKe.TabIndex = 12;
            this.btnThongKe.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThongKe.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThongKe.TextMarginLeft = 0;
            this.btnThongKe.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnThongKe.UseDefaultRadiusAndThickness = true;
            this.btnThongKe.Click += new System.EventHandler(this.btnThongKe_Click);
            // 
            // btnHoaDon
            // 
            this.btnHoaDon.AllowAnimations = true;
            this.btnHoaDon.AllowMouseEffects = true;
            this.btnHoaDon.AllowToggling = false;
            this.btnHoaDon.AnimationSpeed = 200;
            this.btnHoaDon.AutoGenerateColors = false;
            this.btnHoaDon.AutoRoundBorders = false;
            this.btnHoaDon.AutoSizeLeftIcon = true;
            this.btnHoaDon.AutoSizeRightIcon = true;
            this.btnHoaDon.BackColor = System.Drawing.Color.Transparent;
            this.btnHoaDon.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnHoaDon.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHoaDon.BackgroundImage")));
            this.btnHoaDon.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoaDon.ButtonText = "HÓA ĐƠN";
            this.btnHoaDon.ButtonTextMarginLeft = 0;
            this.btnHoaDon.ColorContrastOnClick = 45;
            this.btnHoaDon.ColorContrastOnHover = 45;
            this.btnHoaDon.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnHoaDon.CustomizableEdges = borderEdges4;
            this.btnHoaDon.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHoaDon.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHoaDon.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHoaDon.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHoaDon.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnHoaDon.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHoaDon.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnHoaDon.ForeColor = System.Drawing.Color.White;
            this.btnHoaDon.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHoaDon.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHoaDon.IconLeftPadding = new System.Windows.Forms.Padding(8, 3, 3, 3);
            this.btnHoaDon.IconMarginLeft = 11;
            this.btnHoaDon.IconPadding = 5;
            this.btnHoaDon.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHoaDon.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHoaDon.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHoaDon.IconSize = 25;
            this.btnHoaDon.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnHoaDon.IdleBorderRadius = 40;
            this.btnHoaDon.IdleBorderThickness = 1;
            this.btnHoaDon.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnHoaDon.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.purchase_order_320px;
            this.btnHoaDon.IdleIconRightImage = null;
            this.btnHoaDon.IndicateFocus = false;
            this.btnHoaDon.Location = new System.Drawing.Point(0, 235);
            this.btnHoaDon.Name = "btnHoaDon";
            this.btnHoaDon.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHoaDon.OnDisabledState.BorderRadius = 40;
            this.btnHoaDon.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoaDon.OnDisabledState.BorderThickness = 1;
            this.btnHoaDon.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHoaDon.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHoaDon.OnDisabledState.IconLeftImage = null;
            this.btnHoaDon.OnDisabledState.IconRightImage = null;
            this.btnHoaDon.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnHoaDon.onHoverState.BorderRadius = 40;
            this.btnHoaDon.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoaDon.onHoverState.BorderThickness = 1;
            this.btnHoaDon.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnHoaDon.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHoaDon.onHoverState.IconLeftImage = null;
            this.btnHoaDon.onHoverState.IconRightImage = null;
            this.btnHoaDon.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnHoaDon.OnIdleState.BorderRadius = 40;
            this.btnHoaDon.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoaDon.OnIdleState.BorderThickness = 1;
            this.btnHoaDon.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnHoaDon.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHoaDon.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.purchase_order_320px;
            this.btnHoaDon.OnIdleState.IconRightImage = null;
            this.btnHoaDon.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnHoaDon.OnPressedState.BorderRadius = 40;
            this.btnHoaDon.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoaDon.OnPressedState.BorderThickness = 1;
            this.btnHoaDon.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnHoaDon.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnHoaDon.OnPressedState.IconLeftImage = null;
            this.btnHoaDon.OnPressedState.IconRightImage = null;
            this.btnHoaDon.Size = new System.Drawing.Size(250, 45);
            this.btnHoaDon.TabIndex = 11;
            this.btnHoaDon.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHoaDon.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHoaDon.TextMarginLeft = 0;
            this.btnHoaDon.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnHoaDon.UseDefaultRadiusAndThickness = true;
            this.btnHoaDon.Click += new System.EventHandler(this.btnHoaDon_Click);
            // 
            // btnKho
            // 
            this.btnKho.AllowAnimations = true;
            this.btnKho.AllowMouseEffects = true;
            this.btnKho.AllowToggling = false;
            this.btnKho.AnimationSpeed = 200;
            this.btnKho.AutoGenerateColors = false;
            this.btnKho.AutoRoundBorders = false;
            this.btnKho.AutoSizeLeftIcon = true;
            this.btnKho.AutoSizeRightIcon = true;
            this.btnKho.BackColor = System.Drawing.Color.Transparent;
            this.btnKho.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnKho.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnKho.BackgroundImage")));
            this.btnKho.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKho.ButtonText = "KHO";
            this.btnKho.ButtonTextMarginLeft = 0;
            this.btnKho.ColorContrastOnClick = 45;
            this.btnKho.ColorContrastOnHover = 45;
            this.btnKho.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnKho.CustomizableEdges = borderEdges5;
            this.btnKho.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnKho.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKho.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKho.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKho.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnKho.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnKho.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnKho.ForeColor = System.Drawing.Color.White;
            this.btnKho.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnKho.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnKho.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 3, 3);
            this.btnKho.IconMarginLeft = 11;
            this.btnKho.IconPadding = 6;
            this.btnKho.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnKho.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnKho.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnKho.IconSize = 25;
            this.btnKho.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnKho.IdleBorderRadius = 40;
            this.btnKho.IdleBorderThickness = 1;
            this.btnKho.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnKho.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.warehouse_320px;
            this.btnKho.IdleIconRightImage = null;
            this.btnKho.IndicateFocus = false;
            this.btnKho.Location = new System.Drawing.Point(0, 190);
            this.btnKho.Name = "btnKho";
            this.btnKho.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKho.OnDisabledState.BorderRadius = 40;
            this.btnKho.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKho.OnDisabledState.BorderThickness = 1;
            this.btnKho.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKho.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKho.OnDisabledState.IconLeftImage = null;
            this.btnKho.OnDisabledState.IconRightImage = null;
            this.btnKho.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnKho.onHoverState.BorderRadius = 40;
            this.btnKho.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKho.onHoverState.BorderThickness = 1;
            this.btnKho.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnKho.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnKho.onHoverState.IconLeftImage = null;
            this.btnKho.onHoverState.IconRightImage = null;
            this.btnKho.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnKho.OnIdleState.BorderRadius = 40;
            this.btnKho.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKho.OnIdleState.BorderThickness = 1;
            this.btnKho.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnKho.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnKho.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.warehouse_320px;
            this.btnKho.OnIdleState.IconRightImage = null;
            this.btnKho.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnKho.OnPressedState.BorderRadius = 40;
            this.btnKho.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKho.OnPressedState.BorderThickness = 1;
            this.btnKho.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnKho.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnKho.OnPressedState.IconLeftImage = null;
            this.btnKho.OnPressedState.IconRightImage = null;
            this.btnKho.Size = new System.Drawing.Size(250, 45);
            this.btnKho.TabIndex = 10;
            this.btnKho.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnKho.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnKho.TextMarginLeft = 0;
            this.btnKho.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnKho.UseDefaultRadiusAndThickness = true;
            this.btnKho.Click += new System.EventHandler(this.btnKho_Click);
            // 
            // btnSanPham
            // 
            this.btnSanPham.AllowAnimations = true;
            this.btnSanPham.AllowMouseEffects = true;
            this.btnSanPham.AllowToggling = false;
            this.btnSanPham.AnimationSpeed = 200;
            this.btnSanPham.AutoGenerateColors = false;
            this.btnSanPham.AutoRoundBorders = false;
            this.btnSanPham.AutoSizeLeftIcon = true;
            this.btnSanPham.AutoSizeRightIcon = true;
            this.btnSanPham.BackColor = System.Drawing.Color.Transparent;
            this.btnSanPham.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSanPham.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSanPham.BackgroundImage")));
            this.btnSanPham.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.ButtonText = "SẢN PHẨM";
            this.btnSanPham.ButtonTextMarginLeft = 0;
            this.btnSanPham.ColorContrastOnClick = 45;
            this.btnSanPham.ColorContrastOnHover = 45;
            this.btnSanPham.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnSanPham.CustomizableEdges = borderEdges6;
            this.btnSanPham.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSanPham.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSanPham.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSanPham.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSanPham.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnSanPham.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSanPham.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnSanPham.ForeColor = System.Drawing.Color.White;
            this.btnSanPham.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSanPham.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSanPham.IconLeftPadding = new System.Windows.Forms.Padding(5, 3, 3, 3);
            this.btnSanPham.IconMarginLeft = 11;
            this.btnSanPham.IconPadding = 0;
            this.btnSanPham.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSanPham.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSanPham.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSanPham.IconSize = 25;
            this.btnSanPham.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSanPham.IdleBorderRadius = 40;
            this.btnSanPham.IdleBorderThickness = 1;
            this.btnSanPham.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSanPham.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.product_500px;
            this.btnSanPham.IdleIconRightImage = null;
            this.btnSanPham.IndicateFocus = false;
            this.btnSanPham.Location = new System.Drawing.Point(0, 145);
            this.btnSanPham.Name = "btnSanPham";
            this.btnSanPham.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSanPham.OnDisabledState.BorderRadius = 40;
            this.btnSanPham.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.OnDisabledState.BorderThickness = 1;
            this.btnSanPham.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSanPham.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSanPham.OnDisabledState.IconLeftImage = null;
            this.btnSanPham.OnDisabledState.IconRightImage = null;
            this.btnSanPham.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSanPham.onHoverState.BorderRadius = 40;
            this.btnSanPham.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.onHoverState.BorderThickness = 1;
            this.btnSanPham.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnSanPham.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSanPham.onHoverState.IconLeftImage = null;
            this.btnSanPham.onHoverState.IconRightImage = null;
            this.btnSanPham.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSanPham.OnIdleState.BorderRadius = 40;
            this.btnSanPham.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.OnIdleState.BorderThickness = 1;
            this.btnSanPham.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSanPham.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSanPham.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.product_500px;
            this.btnSanPham.OnIdleState.IconRightImage = null;
            this.btnSanPham.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSanPham.OnPressedState.BorderRadius = 40;
            this.btnSanPham.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanPham.OnPressedState.BorderThickness = 1;
            this.btnSanPham.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnSanPham.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnSanPham.OnPressedState.IconLeftImage = null;
            this.btnSanPham.OnPressedState.IconRightImage = null;
            this.btnSanPham.Size = new System.Drawing.Size(250, 45);
            this.btnSanPham.TabIndex = 9;
            this.btnSanPham.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSanPham.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSanPham.TextMarginLeft = 0;
            this.btnSanPham.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnSanPham.UseDefaultRadiusAndThickness = true;
            this.btnSanPham.Click += new System.EventHandler(this.btnSanPham_Click);
            // 
            // btnKhachHang
            // 
            this.btnKhachHang.AllowAnimations = true;
            this.btnKhachHang.AllowMouseEffects = true;
            this.btnKhachHang.AllowToggling = false;
            this.btnKhachHang.AnimationSpeed = 200;
            this.btnKhachHang.AutoGenerateColors = false;
            this.btnKhachHang.AutoRoundBorders = false;
            this.btnKhachHang.AutoSizeLeftIcon = true;
            this.btnKhachHang.AutoSizeRightIcon = true;
            this.btnKhachHang.BackColor = System.Drawing.Color.Transparent;
            this.btnKhachHang.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnKhachHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnKhachHang.BackgroundImage")));
            this.btnKhachHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.ButtonText = "KHÁCH HÀNG";
            this.btnKhachHang.ButtonTextMarginLeft = 0;
            this.btnKhachHang.ColorContrastOnClick = 45;
            this.btnKhachHang.ColorContrastOnHover = 45;
            this.btnKhachHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnKhachHang.CustomizableEdges = borderEdges7;
            this.btnKhachHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnKhachHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKhachHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKhachHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKhachHang.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnKhachHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnKhachHang.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnKhachHang.ForeColor = System.Drawing.Color.White;
            this.btnKhachHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnKhachHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnKhachHang.IconLeftPadding = new System.Windows.Forms.Padding(5, 3, 3, 3);
            this.btnKhachHang.IconMarginLeft = 11;
            this.btnKhachHang.IconPadding = 0;
            this.btnKhachHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnKhachHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnKhachHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnKhachHang.IconSize = 25;
            this.btnKhachHang.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnKhachHang.IdleBorderRadius = 40;
            this.btnKhachHang.IdleBorderThickness = 1;
            this.btnKhachHang.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnKhachHang.IdleIconLeftImage = global::DoAn.NET.Properties.Resources.popular_man_500px;
            this.btnKhachHang.IdleIconRightImage = null;
            this.btnKhachHang.IndicateFocus = false;
            this.btnKhachHang.Location = new System.Drawing.Point(0, 100);
            this.btnKhachHang.Name = "btnKhachHang";
            this.btnKhachHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKhachHang.OnDisabledState.BorderRadius = 40;
            this.btnKhachHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.OnDisabledState.BorderThickness = 1;
            this.btnKhachHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKhachHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKhachHang.OnDisabledState.IconLeftImage = null;
            this.btnKhachHang.OnDisabledState.IconRightImage = null;
            this.btnKhachHang.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnKhachHang.onHoverState.BorderRadius = 40;
            this.btnKhachHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.onHoverState.BorderThickness = 1;
            this.btnKhachHang.onHoverState.FillColor = System.Drawing.SystemColors.Highlight;
            this.btnKhachHang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnKhachHang.onHoverState.IconLeftImage = null;
            this.btnKhachHang.onHoverState.IconRightImage = null;
            this.btnKhachHang.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnKhachHang.OnIdleState.BorderRadius = 40;
            this.btnKhachHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.OnIdleState.BorderThickness = 1;
            this.btnKhachHang.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnKhachHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnKhachHang.OnIdleState.IconLeftImage = global::DoAn.NET.Properties.Resources.popular_man_500px;
            this.btnKhachHang.OnIdleState.IconRightImage = null;
            this.btnKhachHang.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnKhachHang.OnPressedState.BorderRadius = 40;
            this.btnKhachHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachHang.OnPressedState.BorderThickness = 1;
            this.btnKhachHang.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnKhachHang.OnPressedState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btnKhachHang.OnPressedState.IconLeftImage = null;
            this.btnKhachHang.OnPressedState.IconRightImage = null;
            this.btnKhachHang.Size = new System.Drawing.Size(250, 45);
            this.btnKhachHang.TabIndex = 8;
            this.btnKhachHang.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnKhachHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnKhachHang.TextMarginLeft = 0;
            this.btnKhachHang.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnKhachHang.UseDefaultRadiusAndThickness = true;
            this.btnKhachHang.Click += new System.EventHandler(this.btnKhachHang_Click);
            // 
            // frmAdmin
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(11F, 24F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1217, 702);
            this.Controls.Add(this.panelForm);
            this.Controls.Add(this.panelTieuDe);
            this.Controls.Add(this.panelMenu);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.MinimumSize = new System.Drawing.Size(1100, 700);
            this.Name = "frmAdmin";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ADMIN";
            this.Load += new System.EventHandler(this.frmAdmin_Load);
            this.panelMenu.ResumeLayout(false);
            this.panelLogo.ResumeLayout(false);
            this.panelTieuDe.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panelMenu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDangXuat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCaiDat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThongKe;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHoaDon;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnKho;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSanPham;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnKhachHang;
        private System.Windows.Forms.Panel panelLogo;
        private System.Windows.Forms.Label labelLogo;
        private System.Windows.Forms.Panel panelTieuDe;
        private System.Windows.Forms.Label lbTieuDe;
        private System.Windows.Forms.Panel panelForm;
    }
}